name: Michael Thiesen
url: http://www.micthiesen.ca
dateformat: "%-d %B, %Y"

paginate: 5
paginate_path: /page/:num/

exclude: [
  bower.json,
  CNAME,
  gruntfile.js,
  package.json,
  style.less,
  bower_components,
  node_modules
]

highlighter: pygments

gems:
  - jekyll-sitemap
