name: UBC Supermileage
description: The UBC Supermileage Team
url: http://supermileage.ca
dateformat: "%-d %B, %Y"

paginate: 5
paginate_path: /page/:num/

exclude: [
  CNAME,
  README.md,
  bower.json,
  Gemfile,
  Gemfile.lock,
  gruntfile.js,
  package.json,
  style.less,
  bower_components,
  node_modules
]

highlighter: pygments

gems:
  - jekyll-sitemap
